ALTER TABLE SERVICEGOOD ADD COLUMN WARRANTY BOOLEAN;
UPDATE SERVICEGOOD SET WARRANTY = FALSE;
CREATE INDEX "SERVICEGOOD_IDX" ON CHANGERECORD (SERVICEGOOD_ID ASC NULLS LAST);
CREATE INDEX "STOCKGOOD_IDX" ON CHANGERECORD (STOCKGOOD_ID ASC NULLS LAST);
