ALTER TABLE BUSINESSRECEIPT ADD COLUMN RECEIVERPVNREGNUM VARCHAR(255);
ALTER TABLE BUSINESSRECEIPT ADD COLUMN RECEIVERREALADDRESS VARCHAR(255);
ALTER TABLE BUSINESSRECEIPT ADD COLUMN ADVANCEPAYMENT BOOLEAN;
UPDATE BUSINESSRECEIPT SET ADVANCEPAYMENT = FALSE;