ALTER TABLE STORE ADD COLUMN INVOICEPOSTFIX VARCHAR(255);

ALTER TABLE BUSINESSRECEIPT ADD COLUMN NUMBERIDX BIGINT;
ALTER TABLE BUSINESSRECEIPT ADD COLUMN POSTFIX VARCHAR(255);

ALTER TABLE RECEIPTITEM ADD COLUMN DISCOUNT INTEGER;